# Generated by Django 6.1 on 2026-09-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogposts_views_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogposts",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запись в блоге",
                "verbose_name_plural": "Записи в блоге",
            },
        ),
        migrations.AlterField(
            model_name="blogposts",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовать сразу"),
        ),
    ]
