# Generated by Django 6.1 on 2026-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blogposts_options_alter_blogposts_is_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogposts",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
