# Generated by Django 6.1 on 2026-10-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["price"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
